version: "3"

tasks:
  build:
    desc: Build the app
    cmds:
    - GOFLAGS=-mod=mod go build -o bin/gocli main.go

  run:
    desc: Run the app
    cmds:
    - GOFLAGS=-mod=mode go run main.go

  clean:
    desc: Remove all retrieved *.png files
    cmds:
    - rm *.png
